name: Nyxit Soft Deploy

on:
  # push
  push:
    branches: ["main"]
  # closed pull request
  pull request:
    branches: ["main"]
    types: closed
  # manual
  workflow_dispatch:

jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: TODO
